### ISSUE TITLE
[Feature] Introduce configuration sharing

### ISSUE THREAD

**Issue by geminicaprograms** [softwaremill/adopt-tapir#75]
Add `Share configuration` button (as highlighted below)
![image](https://user-images.githubusercontent.com/3641082/179208028-bbdb911d-df33-429d-8a68-181a88bacee9.png)

that generates link with all configuration passed as URL parameters. Configuration from screenshot would result in the link below
```
https://adopt-tapir.softwaremill.com?addDocumentation=true&addMetrics=true&effect=IOEffect&groupId=org.example&implementationHttp4s&json=Jsoniter&projectName=share
```

Note that clicking on `share` would add the URL to the clipboard.

**Comment by lubarskyy** [comment]
## Parsing query params


## Merging query params with default values
In this step we need to consider following things
- merge query params with default values we provide in form initialization
- validate if parsed query params are of correct type and value, so covering cases like `?effect=test`

**Comment by lubarskyy** [comment]
Some tips on how to approach such feature implementation:

## Parsing query params
I do recommend using a [query-string](https://www.npmjs.com/package/query-string) npm package to interact with query params. Be sure to check documentation for some parsing options.

```typescript
import { parse } from 'query-string';
import { useSearchParams } from 'react-router-dom';

const [searchParams, setSearchParams] = useSearchParams();
const queryParams = parse(searchParams.toString(), { parseBooleans: true });
 ```

## Merging query params with default values
In this step we need to consider following things:
- merge query params with default values we provide in form initialization,
- validate if parsed query params are of correct type and value, so covering cases like `?effect=test` - think of some fallback strategy here.

NOTE: one caveat here might be that when we set some field to a default value and the we try to reset it by `form.resetField('fieldName')` it won't fallback to `undefined` or `""`, but to a value we provided as default. I do believe this should work just fine:

```typescript
form.resetField('implementation', { defaultValue: '' });
```

## Updating location URL
After we parse query params and feed them into form as our initial values we need to update location URL, preferably we want to remove whole query string part for two reasons:
- every time user will refresh a page, he will get the same set of data, which might lead to inconsistent behavior --> _why sometimes if I refresh the page I get the empty form and sometimes not?_ :thinking: 
- we do not have to update query params on every form value change in order to keep it in sync,

So in order to mitigate the above we need to set an side effect that will clear query params. Example below:
```typescript
useEffect(() => {
  setSearchParams({});
}, [setSearchParams]);
```
## Retrieving form state and turning it into link:
We need to turn our form values into a URL string:
```typescript
const values = form.getValues() // retrieves form values at the time of executution
const urlToShare = stringifyUrl({ url: // get url here, query: values }) // stringifyUrl method from query-param package

// share button onClick handler:
navigator.clipboard.writeText(urlToShare) // warning async method - https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText
```
